USE [master]
GO
/****** Object:  Database [FileSizes]    Script Date: 2/11/2026 3:51:30 PM ******/
CREATE DATABASE [FileSizes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileSizes', FILENAME = N'F:\Data\FileSizes.mdf' , SIZE = 96256000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024000KB )
 LOG ON 
( NAME = N'FileSizes_log', FILENAME = N'G:\Logs\FileSizes_log.ldf' , SIZE = 248320000KB , MAXSIZE = 2048GB , FILEGROWTH = 1024000KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FileSizes] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileSizes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FileSizes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FileSizes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FileSizes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FileSizes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FileSizes] SET ARITHABORT OFF 
GO
ALTER DATABASE [FileSizes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FileSizes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FileSizes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FileSizes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FileSizes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FileSizes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FileSizes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FileSizes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FileSizes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FileSizes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FileSizes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FileSizes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FileSizes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FileSizes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FileSizes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FileSizes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FileSizes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FileSizes] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FileSizes] SET  MULTI_USER 
GO
ALTER DATABASE [FileSizes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FileSizes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FileSizes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FileSizes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FileSizes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FileSizes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FileSizes', N'ON'
GO
ALTER DATABASE [FileSizes] SET QUERY_STORE = ON
GO
ALTER DATABASE [FileSizes] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
ALTER DATABASE [FileSizes] SET  READ_WRITE 
GO
