USE [SUSDB_Reports]
GO

/****** Object:  Index [idx_Date]    Script Date: 4/10/2024 11:22:20 AM ******/
CREATE NONCLUSTERED INDEX [idx_Date] ON [dbo].[tb_DailySummariesPerDownstreamServer]
(
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO


