{
 "title": "Backlog Patching Schedule",
 "tags": [ "WSUS Dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Patching Backlog",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "This list identifies systems that require updates to meet current patch levels. These systems pose a security vulnerability within the SS&C network.\n\nThe Windows Infrastructure team schedules patching sessions every Saturday to address these systems in batches of 10.\n\nThe panel labeled \"Week 1\" represents the current week's patching efforts. Weeks 2-4 are displayed to allow product teams to anticipate upcoming systems. This list is updated daily; thus, the lineup of systems may change. Please ensure to review it regularly.\n\nSystems will be brought up to the current standard and may require multiple reboots. Change controls will be created and reviewed weekly in the Change Advisory Board (CAB) meetings."
   },
   "targets": [
    { "dataset": "SUSDB" }
   ]
  },
  {
   "title": "Update Process outline",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "We will provide an overview of how the update process will function here"
   },
   "targets": [
    { "dataset": "SUSDB" }
   ]
  },
  {
   "title": "Week 1",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "SUSDB",
     "rawSql": "SELECT [ComputerId],[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer] )\r\nORDER BY [Needed] DESC\r\nOFFSET 0 ROWS\r\nFETCH NEXT 10 ROWS ONLY;"
    }
   ]
  },
  {
   "title": "Week 2",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "SUSDB",
     "rawSql": "SELECT [ComputerId],[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer] )\r\nORDER BY [Needed] DESC\r\nOFFSET 10 ROWS\r\nFETCH NEXT 10 ROWS ONLY;"
    }
   ]
  },
  { "title": "Week 3 and Week 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Week 3",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "SUSDB",
     "rawSql": "SELECT [ComputerId],[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer] )\r\nORDER BY [Needed] DESC\r\nOFFSET 20 ROWS\r\nFETCH NEXT 10 ROWS ONLY;"
    }
   ]
  },
  {
   "title": "Week 4",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "dataset": "SUSDB",
     "rawSql": "SELECT [ComputerId],[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer] )\r\nORDER BY [Needed] DESC\r\nOFFSET 30 ROWS\r\nFETCH NEXT 10 ROWS ONLY;"
    }
   ]
  },
  {
   "title": "All Systems requiring more than 10 Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Systems",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "dataset": "SUSDB",
       "rawSql": "SELECT [ComputerId],[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer])\r\n\t\tand [Needed] >= 10\r\nORDER BY [Needed] DESC\r\n"
      }
     ]
    }
   ]
  }
 ]
}