{
 "title": "Windows Update Overview",
 "tags": [ "WSUS Dashboard" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "frmMsrcSeverity",
    "label": "MSRC Severity",
    "query": "select distinct [MsrcSeverity]\nFROM [SUSDB].[PUBLIC_VIEWS].[vUpdate]"
   },
   { "name": "frmShowComputerCount", "label": "Computer Count", "query": "False, True" }
  ]
 },
 "panels": [
  {
   "title": "System Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(CASE WHEN Stat = 'TotalComputers' THEN Value END) AS [Total],\r\n  MAX(CASE WHEN Stat = 'ComputersNeedingUpdates' THEN Value END) AS [Needing Updates]\r\nFROM [SUSDB_Reports].[dbo].[tb_MissingPatchCounts];"
    }
   ]
  },
  {
   "title": "Required Patches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(CASE WHEN Stat = 'Critical' THEN Value END) AS Critical,\r\n  MAX(CASE WHEN Stat = 'Important' THEN Value END) AS Important,\r\n  MAX(CASE WHEN Stat = 'Moderate' THEN Value END) AS Moderate,\r\n  MAX(CASE WHEN Stat = 'Low' THEN Value END) AS Low,\r\n  MAX(CASE WHEN Stat = 'Unspecified' THEN Value END) AS Unspecified\r\nFROM [SUSDB_Reports].[dbo].[tb_MissingPatchCounts];"
    }
   ]
  },
  {
   "title": "Needed Patches by Patch Severity Ratings ",
   "type": "timeseries",
   "description": "# Patch Severity Ratings\n\nThis document provides definitions for the severity ratings of software updates.\n\n## Severity Levels\n\n- **Critical**\n  - The update fixes a vulnerability whose exploitation could allow for the propagation of an Internet worm without user action.\n\n- **Important**\n  - The update fixes a vulnerability whose exploitation could result in the compromise of the confidentiality, integrity, or availability of users' data, or of the integrity or availability of processing resources.\n\n- **Low**\n  - The update fixes a vulnerability whose exploitation is extremely difficult, or whose impact is minimal.\n\n- **Moderate**\n  - The update fixes a vulnerability whose exploitation is mitigated to a significant degree by factors such as default configuration, auditing, or difficulty of exploitation.\n\n- **Unspecified**\n  - The update does not have a severity rating.\n",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "DECLARE @MsrcSeverity nvarchar(15);\r\nSET @MsrcSeverity = 'Critical';\r\n\r\nDECLARE @SQL nvarchar(MAX);\r\nSET @SQL = '\r\nSELECT \r\n    [DATE],\r\n    [MsrcSeverity],\r\n    COUNT(*) AS ' + QUOTENAME(@MsrcSeverity) + '\r\nFROM \r\n    [SUSDB_Reports].[dbo].[tb_UpdatesNeededByComputerHistory]\r\nWHERE \r\n    [MsrcSeverity] = @MsrcSeverity \r\nGROUP BY \r\n    [DATE],\r\n    [MsrcSeverity]\r\nORDER BY \r\n    [DATE], \r\n    [MsrcSeverity];\r\n';\r\n\r\nDECLARE @RunScript as bit;\r\n\r\nSELECT @RunScript = \r\n  CASE\r\n    WHEN @MsrcSeverity IN ($frmMsrcSeverity)\r\n    or 'All' IN ($frmMsrcSeverity) THEN 1\r\n    ELSE 0\r\n  END\r\n\r\nIF @RunScript = 1\r\nBEGIN\r\n    EXEC sp_executesql @SQL, N'@MsrcSeverity nvarchar(15)', @MsrcSeverity = @MsrcSeverity;\r\nEND\r\n"
    },
    {
     "rawSql": "DECLARE @MsrcSeverity nvarchar(15);\r\nSET @MsrcSeverity = 'Important';\r\n\r\nDECLARE @SQL nvarchar(MAX);\r\nSET @SQL = '\r\nSELECT \r\n    [DATE],\r\n    [MsrcSeverity],\r\n    COUNT(*) AS ' + QUOTENAME(@MsrcSeverity) + '\r\nFROM \r\n    [SUSDB_Reports].[dbo].[tb_UpdatesNeededByComputerHistory]\r\nWHERE \r\n    [MsrcSeverity] = @MsrcSeverity \r\nGROUP BY \r\n    [DATE],\r\n    [MsrcSeverity]\r\nORDER BY \r\n    [DATE], \r\n    [MsrcSeverity];\r\n';\r\n\r\nDECLARE @RunScript as bit;\r\n\r\nSELECT @RunScript = \r\n  CASE\r\n    WHEN @MsrcSeverity IN ($frmMsrcSeverity)\r\n    or 'All' IN ($frmMsrcSeverity) THEN 1\r\n    ELSE 0\r\n  END\r\n\r\nIF @RunScript = 1\r\nBEGIN\r\n    EXEC sp_executesql @SQL, N'@MsrcSeverity nvarchar(15)', @MsrcSeverity = @MsrcSeverity;\r\nEND\r\n"
    },
    {
     "rawSql": "DECLARE @MsrcSeverity nvarchar(15);\r\nSET @MsrcSeverity = 'Low';\r\n\r\nDECLARE @SQL nvarchar(MAX);\r\nSET @SQL = '\r\nSELECT \r\n    [DATE],\r\n    [MsrcSeverity],\r\n    COUNT(*) AS ' + QUOTENAME(@MsrcSeverity) + '\r\nFROM \r\n    [SUSDB_Reports].[dbo].[tb_UpdatesNeededByComputerHistory]\r\nWHERE \r\n    [MsrcSeverity] = @MsrcSeverity \r\nGROUP BY \r\n    [DATE],\r\n    [MsrcSeverity]\r\nORDER BY \r\n    [DATE], \r\n    [MsrcSeverity];\r\n';\r\n\r\nDECLARE @RunScript as bit;\r\n\r\nSELECT @RunScript = \r\n  CASE\r\n    WHEN @MsrcSeverity IN ($frmMsrcSeverity)\r\n    or 'All' IN ($frmMsrcSeverity) THEN 1\r\n    ELSE 0\r\n  END\r\n\r\nIF @RunScript = 1\r\nBEGIN\r\n    EXEC sp_executesql @SQL, N'@MsrcSeverity nvarchar(15)', @MsrcSeverity = @MsrcSeverity;\r\nEND\r\n"
    },
    {
     "rawSql": "DECLARE @MsrcSeverity nvarchar(15);\r\nSET @MsrcSeverity = 'Moderate';\r\n\r\nDECLARE @SQL nvarchar(MAX);\r\nSET @SQL = '\r\nSELECT \r\n    [DATE],\r\n    [MsrcSeverity],\r\n    COUNT(*) AS ' + QUOTENAME(@MsrcSeverity) + '\r\nFROM \r\n    [SUSDB_Reports].[dbo].[tb_UpdatesNeededByComputerHistory]\r\nWHERE \r\n    [MsrcSeverity] = @MsrcSeverity \r\nGROUP BY \r\n    [DATE],\r\n    [MsrcSeverity]\r\nORDER BY \r\n    [DATE], \r\n    [MsrcSeverity];\r\n';\r\n\r\nDECLARE @RunScript as bit;\r\n\r\nSELECT @RunScript = \r\n  CASE\r\n    WHEN @MsrcSeverity IN ($frmMsrcSeverity)\r\n    or 'All' IN ($frmMsrcSeverity) THEN 1\r\n    ELSE 0\r\n  END\r\n\r\nIF @RunScript = 1\r\nBEGIN\r\n    EXEC sp_executesql @SQL, N'@MsrcSeverity nvarchar(15)', @MsrcSeverity = @MsrcSeverity;\r\nEND\r\n"
    },
    {
     "rawSql": "DECLARE @MsrcSeverity nvarchar(15);\r\nSET @MsrcSeverity = 'Unspecified';\r\n\r\nDECLARE @SQL nvarchar(MAX);\r\nSET @SQL = '\r\nSELECT \r\n    [DATE],\r\n    [MsrcSeverity],\r\n    COUNT(*) AS ' + QUOTENAME(@MsrcSeverity) + '\r\nFROM \r\n    [SUSDB_Reports].[dbo].[tb_UpdatesNeededByComputerHistory]\r\nWHERE \r\n    [MsrcSeverity] = @MsrcSeverity \r\nGROUP BY \r\n    [DATE],\r\n    [MsrcSeverity]\r\nORDER BY \r\n    [DATE], \r\n    [MsrcSeverity];\r\n';\r\n\r\nDECLARE @RunScript as bit;\r\n\r\nSELECT @RunScript = \r\n  CASE\r\n    WHEN @MsrcSeverity IN ($frmMsrcSeverity)\r\n    or 'All' IN ($frmMsrcSeverity) THEN 1\r\n    ELSE 0\r\n  END\r\n\r\nIF @RunScript = 1\r\nBEGIN\r\n    EXEC sp_executesql @SQL, N'@MsrcSeverity nvarchar(15)', @MsrcSeverity = @MsrcSeverity;\r\nEND\r\n"
    },
    {
     "dataset": "SUSDB",
     "rawSql": "SELECT \r\n    [DATE],\r\n    COUNT(DISTINCT [ComputerId]) AS [System Count]\r\nFROM \r\n    [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE\r\n    ('$frmShowComputerCount' = 'true' OR 1=0)\r\nGROUP BY \r\n    [DATE]\r\nORDER BY \r\n    [DATE];\r\n"
    }
   ]
  },
  {
   "title": "Top 50 Systems Requiring Updates",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT TOP (50) [ComputerId]\r\n\t,[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer] )\r\nORDER BY [Needed] DESC"
    }
   ]
  },
  {
   "title": "Updates Required by Domain",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT [Domain]\r\n      ,[Systems]\r\n      ,[Critical]\r\n      ,[Important]\r\n      ,[Moderate]\r\n      ,[Low]\r\n      ,[Unspecified]\r\n  FROM [SUSDB_Reports].[dbo].[tb_UpdateSummaryByDomain]\r\nORDER BY Domain;\r\n"
    }
   ]
  },
  {
   "title": "Top 50 Systems with Failed Updates",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT TOP (50) [ComputerId]\r\n\t,[FullDomainName] AS [FQDN]\r\n\t,[TargetGroupName] AS [Target Group]\r\n\t,[Needed]\r\n\t,[Failed]\r\n\t,CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + CAST([OSBuildNumber] AS NVARCHAR(10)) + \r\n\tCASE \r\n\t\tWHEN [OSServicePackMajorNumber] > 0\r\n\t\t\tTHEN ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10))\r\n\t\tELSE ''\r\n\tEND AS [OS Version]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [Date] = ( SELECT MAX([Date])\r\n\t\tFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer] )\r\nORDER BY [Failed] DESC"
    }
   ]
  }
 ]
}