{
 "title": "WSUS - Server Error Logs",
 "tags": [ "WSUS Dashboard" ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Client Download Errors",
   "type": "table",
   "description": "WSUS Clients with download errors over the past 30 days",
   "gridPos": { "h": 23, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Client, COUNT(*) as ErrorCount\r\nFROM SUSDB_Reports.dbo.vw_GetWSUSEvents \r\nWHERE MessageTemplate = 'Error: Download failed.' \r\nAND $__timeFilter(TimeAtTarget)\r\nGROUP BY Client\r\nORDER BY Client ASC \r\n"
    }
   ]
  },
  {
   "title": "Install Errors",
   "type": "table",
   "description": "WSUS Clients with Install errors over the past 30 days",
   "gridPos": { "h": 23, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select Client, count(*) as ErrorCount\r\nfrom SUSDB_Reports.dbo.vw_GetWSUSEvents \r\nWHERE MessageTemplate = 'Installation Failure: Windows failed to install the following update with error %1: %2.' and \r\n$__timeFilter(TimeAtTarget)\r\nGROUP BY Client\r\nORDER BY Client ASC "
    }
   ]
  },
  {
   "title": "Windows Update Client failed to detect",
   "type": "table",
   "description": "Windows Update Client failed to detect errors over the past 30 days",
   "gridPos": { "h": 23, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select Client, count(*) as ErrorCount\r\nfrom SUSDB_Reports.dbo.vw_GetWSUSEvents \r\nWHERE MessageTemplate = 'Windows Update Client failed to detect with error %1.' and \r\n$__timeFilter(TimeAtTarget)\r\nGROUP BY Client\r\nORDER BY Client ASC "
    }
   ]
  }
 ]
}