{
 "title": "WSUS - Update Report",
 "tags": [ "WSUS Dashboard" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "SearchTerm", "label": "Search Term" },
   {
    "name": "UpdateID",
    "query": "DECLARE @SQLQuery NVARCHAR(MAX)\nDECLARE @IsGUID BIT\n\nSET @IsGUID = [SUSDB_Reports].dbo.IsValidGUID('$SearchTerm')\n\nIF @IsGUID = 1\nBEGIN\n    -- Construct SQL query for GUID comparison\n    SET @SQLQuery = N'SELECT TOP 1 [UpdateId]\n                      FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update]\n                      WHERE [UpdateId] = ''' + CAST('$SearchTerm' AS NVARCHAR(MAX)) + ''''\nEND\nELSE\n\tBEGIN\n\t\t-- Construct SQL query for KnowledgebaseArticle and DefaultTitle comparison\n\t\tSET @SQLQuery = N'SELECT TOP 1 [UpdateId]\n\t\t\t\t\t\t  FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update]\n\t\t\t\t\t\t  WHERE [KnowledgebaseArticle] = ''' + '$SearchTerm' + '''\n\t\t\t\t\t\t  OR [DefaultTitle] = ''' + '$updatename' + ''''\n\tEND\n\n-- Execute the constructed SQL query\nEXEC sp_executesql @SQLQuery\n"
   },
   {
    "name": "updatename",
    "label": "Update Title",
    "query": "DECLARE @SQLQuery NVARCHAR(MAX)\nDECLARE @IsGUID BIT\n\nSET @IsGUID = [SUSDB_Reports].dbo.IsValidGUID('$SearchTerm')\n\nIF @IsGUID = 1\nBEGIN\n    -- Construct SQL query for GUID comparison\n    SET @SQLQuery = N'SELECT [DefaultTitle]\n                      FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update]\n                      WHERE [UpdateId] = ''' + CAST('$SearchTerm' AS NVARCHAR(MAX)) + ''''\nEND\nELSE\nBEGIN\n    -- Construct SQL query for KnowledgebaseArticle and DefaultTitle comparison\n    SET @SQLQuery = N'SELECT [DefaultTitle]\n                      FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update]\n                      WHERE [KnowledgebaseArticle] = ''' + '$SearchTerm' + '''\n                      OR [DefaultTitle] LIKE ''%' + '$SearchTerm' + '%'''\nEND\n\n-- Execute the constructed SQL query\nEXEC sp_executesql @SQLQuery"
   },
   {
    "name": "UpdateDescription",
    "query": "IF ('$UpdateID' IS NULL OR '$UpdateID' = '')\nBEGIN\n    SELECT 'Invalid Query' as [Message]\nEND\nELSE\nBEGIN\n    SELECT S.[DefaultDescription]\n    FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update] AS S\n    WHERE S.[UpdateId] = '$UpdateID'\nEND\n"
   },
   {
    "name": "UpdateURL",
    "query": "IF ('$UpdateID' IS NULL OR '$UpdateID' = '')\nBEGIN\n\tSELECT 'Invalid Query' AS [Message]\nEND\nELSE\nBEGIN\n\tSELECT URL.[URL]\n\tFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update] AS S\n\tLEFT JOIN [SUSDB].[PUBLIC_VIEWS].[vUpdateAdditionalInfoUrl] AS URL ON S.[UpdateId] = URL.[UpdateId]\n\t\tAND [LocaleId] = 1033\n\tWHERE S.[UpdateId] = ('$UpdateID')\nEND"
   },
   {
    "name": "revisionnumber",
    "query": "SELECT CAST([RevisionNumber] AS INT) AS [RevisionNumber]\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update]\nWHERE [UpdateId] = ('$UpdateID')\n"
   }
  ]
 },
 "panels": [
  {
   "title": "$updatename Description",
   "type": "text",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "$UpdateDescription\r\n\r\nMore Information: ${UpdateURL}"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT S.[Needed] AS [Needed On]\r\n      ,S.[Failed] AS [Failed On]\r\n  FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update] AS S\r\n  WHERE S.[UpdateId] = ('$UpdateID')"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT [Date]\r\n      ,[Needed]\r\n      ,[Failed]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerUpdate]\r\nWHERE [UpdateId] = ('$UpdateID')"
    }
   ]
  },
  {
   "title": "Details: $updatename",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT S.[KnowledgebaseArticle] AS [KB]\r\n      ,S.[IsDeclined] AS [Declined]\r\n      ,S.[MsrcSeverity] as [MSRC Severity]\r\n      ,S.[SecurityBulletin] AS [Security Bulletin]\r\n      ,S.[InstallationCanRequestUserInput] as [User Input Needed]\r\n      ,S.[InstallationRequiresNetworkConnectivity] as [Requires Network]\r\n      ,S.[InstallationImpact] AS [Installation Impact]\r\n      ,S.[InstallationRebootBehavior] as [Reboot Behavior]\r\n      ,S.[Classification]\r\n      ,M.[UninstallationSupported] as [Uninstallation Supported]\r\n      ,M.[IsLatestRevision] as [Is Latest Revision]\r\n  FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update] AS S\r\n  LEFT JOIN [SUSDB].[dbo].[vwMinimalUpdate] AS M ON S.UpdateID = M.UpdateID\r\n  WHERE S.[UpdateId] = ('$UpdateID')"
    }
   ]
  },
  {
   "title": "Dates",
   "type": "table",
   "description": "In the context of a WSUS (Windows Server Update Services) server, the terms \"Arrival Date\" and \"Creation Date\" refer to different aspects of an update:\n\n1. **Arrival Date**: \n    - This is the date when the update was actually received by your WSUS server.\n    - It indicates when the update became available to the WSUS server from Microsoft's update servers.\n    - This date is important for WSUS administrators because it helps in tracking when new updates are brought into the WSUS system.\n    - It's useful for understanding the timeline of updates availability within your WSUS infrastructure.\n\n\n2. **Creation Date**:\n    - This refers to the date when the update was originally created by Microsoft.\n    - It's the date when the update was finalized and made ready for distribution.\n    - The Creation Date is important for understanding the age of the update and for some administrative purposes, like coordinating updates with known issues or release notes published by Microsoft.\n",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT 'Arrival Date' AS [Property], CONVERT(VARCHAR, S.[ArrivalDate]) AS Value\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update] AS S\r\nLEFT JOIN [SUSDB].[PUBLIC_VIEWS].[vUpdateAdditionalInfoUrl] AS URL \r\n    ON S.[UpdateId] = URL.[UpdateId] and [LocaleId] = 1033\r\nWHERE S.[UpdateId] = ('$UpdateID')\r\n\r\nUNION ALL\r\n\r\nSELECT 'Creation Date', CONVERT(VARCHAR, S.[CreationDate])\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Update] AS S\r\nLEFT JOIN [SUSDB].[PUBLIC_VIEWS].[vUpdateAdditionalInfoUrl] AS URL \r\n    ON S.[UpdateId] = URL.[UpdateId] and [LocaleId] = 1033\r\nWHERE S.[UpdateId] = ('$UpdateID')\r\n\r\n"
    }
   ]
  },
  {
   "title": "Updates That Supersede This Update",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "DECLARE @revisionNumber int;\r\nSET @revisionNumber = CAST(($revisionnumber) as INT)\r\n\r\nEXEC [SUSDB_Reports].[dbo].[spGetUpdatesThatSupersedeUpdate] @updateID = '$UpdateID', @revisionNumber = @revisionNumber "
    }
   ]
  },
  {
   "title": "Updates That Are Superseded By This Update",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "DECLARE @revisionNumber int;\r\nSET @revisionNumber = CAST(($revisionnumber) as INT)\r\n\r\nEXEC [SUSDB_Reports].[dbo].[spGetUpdatesSupersededByUpdate] @updateID = '$UpdateID', @revisionNumber = @revisionNumber "
    }
   ]
  },
  {
   "title": "Updates Required By This Update",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "DECLARE @revisionNumber int;\r\nSET @revisionNumber = CAST(($revisionnumber) as INT)\r\n\r\nEXEC [SUSDB_Reports].[dbo].[spGetUpdatesRequiredByUpdate] @updateID = '$UpdateID', @revisionNumber = @revisionNumber "
    }
   ]
  },
  {
   "title": "Updates That Require This Update",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "DECLARE @revisionNumber int;\r\nSET @revisionNumber = CAST(($revisionnumber) as INT)\r\n\r\nEXEC [SUSDB_Reports].[dbo].[spGetUpdatesThatRequireUpdate] @updateID = '$UpdateID', @revisionNumber = @revisionNumber "
    }
   ]
  },
  {
   "title": "Computers that need $updatename",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  [ComputerName],\r\n  [SummarizationState],\r\n  [Action],\r\n  [TargetGroupName],\r\n  [ComputerID]\r\nFROM\r\n  [SUSDB_Reports].[dbo].[vw_UpdatesNeededByComputer]\r\nWHERE\r\n  [UpdateID] = '$UpdateID'"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  }
 ]
}