{
 "title": "WSUS - Computer Report",
 "tags": [ "WSUS Dashboard" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ComputerID",
    "label": "WSUS Computer ID",
    "query": "SELECT TOP 1 [ComputerId]\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\nWHERE[ComputerId] = ('$SearchTerm') or [FullDomainName] like ('%$SearchTerm%')\nORDER BY [FullDomainName]"
   },
   {
    "name": "computername",
    "query": "SELECT TOP 1 [FullDomainName]\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\nWHERE[ComputerId] = ('$SearchTerm') or [FullDomainName] like ('%$SearchTerm%')\nORDER BY [FullDomainName]"
   },
   {
    "name": "osversion",
    "query": "SELECT \n    CAST([OSMajorVersion] AS NVARCHAR(10)) + '.' + \n    CAST([OSMinorVersion] AS NVARCHAR(10)) + '.' + \n    CAST([OSBuildNumber] AS NVARCHAR(10)) + \n    CASE \n        WHEN [OSServicePackMajorNumber] > 0 THEN \n            ' SP' + CAST([OSServicePackMajorNumber] AS NVARCHAR(10)) + '.' + \n            CAST([OSServicePackMinorNumber] AS NVARCHAR(10))\n        ELSE \n            ''\n    END AS OSVersionDetails\nFROM \n    [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\nWHERE \n    [ComputerId] = ('$ComputerID') "
   },
   { "name": "SearchTerm", "label": "Search Term" },
   {
    "name": "patching_group",
    "query": "DECLARE @Results TABLE (\n    [patching_group] NVARCHAR(25)\n);\n\n-- Store the results of the first query in the table variable\nINSERT INTO @Results ([patching_group])\nselect top 1 [patching_group]\nfrom [InfrasrtructureInventory].[dbo].[Merged_VMData_v2]\nwhere dns_name = '$computername';\n\n-- Check if any rows were returned\nIF (SELECT COUNT(*) FROM @Results) > 0\n    -- If rows exist, select them\n    SELECT * FROM @Results;\nELSE\n    -- If no rows exist, return a message\n    SELECT 'Schedule Not Found' AS [patching_group];"
   }
  ]
 },
 "panels": [
  {
   "title": "System Details: $computername ($osversion)",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT [OSDescription] as OS\r\n       ,[IPAddress] as [IP Address]\r\n       ,'$patching_group' as 'Patching Schedule'\r\n      ,[TargetGroupName] AS [WSUS Target Group]\r\n      ,[Needed]\r\n      ,[Failed]\r\n      ,[OSLocale] AS [OS Locale]\r\n      ,[ComputerMake] AS [Computer Make]\r\n      ,[ComputerModel] AS [Computer Model]\r\n      ,[ProcessorArchitecture] AS [CPU Arch.]\r\n      ,[ClientVersion] AS [Client Version]\r\n      \r\n  FROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\r\nwhere [ComputerId] = ('$ComputerID')"
    }
   ]
  },
  {
   "title": "Reporting Status",
   "type": "table",
   "description": "##### WSUS Client Timestamps Explanation\n\n###### EffectiveLastDetectionTime\n- **Description**: Represents the most recent time the client successfully checked in with the WSUS server to detect updates. This timestamp updates each time a new detection cycle completes and updates are found to be applicable.\n\n###### LastReportedStatusTime\n- **Description**: Indicates the last time the client sent status information to the WSUS server. This includes reports on installed updates, failed installations, and updates that are not applicable. It's pivotal for monitoring the current update status directly from the client.\n\n###### LastSyncTime\n- **Description**: This timestamp shows the last time the client successfully synchronized with the WSUS server. During synchronization, the client retrieves update metadata from the server to assess which updates are applicable.\n\n###### CreatedTime\n- **Description**: This is the time when the WSUS client record was first created on the WSUS server. It essentially marks the initiation of the client's interaction with the WSUS infrastructure.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT 'EffectiveLastDetectionTime' AS Process, CAST([EffectiveLastDetectionTime] AS NVARCHAR(MAX)) AS [Date/Time]\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\r\nWHERE [ComputerId] = ('$ComputerID')\r\nUNION ALL\r\nSELECT 'LastReportedStatusTime', CAST([LastReportedStatusTime] AS NVARCHAR(MAX))\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\r\nWHERE [ComputerId] = ('$ComputerID')\r\nUNION ALL\r\nSELECT 'LastSyncTime', CAST([LastSyncTime] AS NVARCHAR(MAX))\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\r\nWHERE [ComputerId] = ('$ComputerID')\r\nUNION ALL\r\nSELECT 'CreatedTime', CAST([CreatedTime] AS NVARCHAR(MAX))\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\r\nWHERE [ComputerId] = ('$ComputerID')\r\n"
    }
   ]
  },
  {
   "title": "Updates required: $computername (more info, scroll right)",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT [Action]\r\n      ,[KB]\r\n      ,[UpdateTitle] AS [Patch Description]\r\n      ,[SummarizationState]\r\n      ,[IsDeclined] as [Declined]\r\n      ,[MsrcSeverity] as [MSRC Severity]\r\n      ,[SecurityBulletin] AS [Security Bulletin]\r\n      ,[InstallationCanRequestUserInput] as [Can Request User Input]\r\n      ,[InstallationRequiresNetworkConnectivity] as [Requires Network Connectivity]\r\n      ,[InstallationImpact] AS [Installation Impact]\r\n      ,[InstallationRebootBehavior] as [Reboot Behavior]\r\n      ,[UpdateId]\r\n  FROM [SUSDB_Reports].[dbo].[vw_UpdatesNeededByComputer]\r\n  where [ComputerID] = ('$ComputerID')"
    }
   ]
  },
  {
   "title": "Update required by Severity",
   "type": "piechart",
   "description": "##### Vulnerability Ratings and Descriptions\n\n###### Critical\n- **Description**: Exploitation could allow code execution without user interaction, such as through self-propagating malware or when visiting a web page or opening an email.\n- **Recommendation**: Apply Critical updates immediately.\n\n###### Important\n- **Description**: Exploitation could compromise the confidentiality, integrity, or availability of user data, or of processing resources. This includes scenarios where a client is compromised with warnings or prompts, or where sequences of user actions do not generate prompts or warnings.\n- **Recommendation**: Apply Important updates at the earliest opportunity.\n\n###### Moderate\n- **Description**: The impact of the vulnerability is significantly mitigated by factors such as authentication requirements or applicability only to non-default configurations.\n- **Recommendation**: Consider applying the security update.\n\n###### Low\n- **Description**: The impact of the vulnerability is comprehensively mitigated by the characteristics of the affected component.\n- **Recommendation**: Evaluate whether to apply the security update to the affected systems.\n\n###### Unspecified\n- **Description**: Updates for which no specific severity level has been assigned by the update publisher. This could be due to various reasons, such as updates that do not directly impact the security of the system (e.g., minor feature enhancements or non-critical bug fixes).  This typically includes documentation updates, certain non-security related updates, or updates where the severity is not applicable. The absence of a rating does not necessarily indicate the update's lack of importance, but rather that it does not fit into the traditional severity classifications.\n- **Recommendation**: These updates can still be significant for system functionality or user experience. Administrators should review these updates based on the content and the affected components to decide their deployment strategy.\n\nFor more information, please see: [Microsoft Security Update Severity Rating System](https://www.microsoft.com/en-us/msrc/security-update-severity-rating-system)\n",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT [MsrcSeverity], count(*) as count\r\nFROM (SELECT DISTINCT [Action]\r\n      ,[KB]\r\n      ,[UpdateTitle]\r\n      ,[SummarizationState]\r\n      ,[IsDeclined]\r\n      ,[MsrcSeverity]\r\n      ,[SecurityBulletin]\r\n      ,[InstallationCanRequestUserInput]\r\n      ,[InstallationRequiresNetworkConnectivity]\r\n      ,[InstallationImpact]\r\n      ,[InstallationRebootBehavior]\r\n  FROM [SUSDB_Reports].[dbo].[vw_UpdatesNeededByComputer]\r\n  where [ComputerID] = ('$ComputerID')) as q\r\nGroup BY [MsrcSeverity]"
    }
   ]
  },
  {
   "title": "WSUS Event Log: $computername",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "DECLARE @Results TABLE (\r\n    [Action] NVARCHAR(MAX),\r\n    [UPDATE] NVARCHAR(MAX),\r\n    [Time at Client] DATETIME,\r\n    [Time at WSUS Server] DATETIME,\r\n    [State] NVARCHAR(MAX)\r\n);\r\n\r\n-- Store the results of the first query in the table variable\r\nINSERT INTO @Results ([Action], [UPDATE], [Time at Client], [Time at WSUS Server], [State])\r\nSELECT [MessageTemplate] AS [Action],\r\n       [DefaultTitle] AS [UPDATE],\r\n       [TimeAtTarget] AS [Time at Client],\r\n       [TimeAtServer] AS [Time at WSUS Server],\r\n       [State]\r\nFROM [SUSDB_Reports].[dbo].[vw_GetWSUSEvents]\r\nWHERE [ComputerId] = ('$ComputerID');\r\n\r\n-- Check if any rows were returned\r\nIF (SELECT COUNT(*) FROM @Results) > 0\r\n    -- If rows exist, select them\r\n    SELECT * FROM @Results\r\n    ORDER BY [Time at Client] DESC ;\r\nELSE\r\n    -- If no rows exist, return a message\r\n    SELECT 'No Data Present' AS Message;\r\n"
    }
   ]
  },
  {
   "title": "Patch status over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  [Date],\r\n  [Needed],\r\n  [Failed]\r\nFROM [SUSDB_Reports].[dbo].[tb_DailySummariesPerComputer]\r\nWHERE [ComputerID] = ('$ComputerID')\r\n\r\nUNION\r\n\r\nSELECT\r\n  GetDate() AS DATE,\r\n  [Needed],\r\n  [Failed]\r\nFROM [SUSDB_Reports].[dbo].[vw_SummaryStatus_Computer]\r\nWHERE [ComputerID] = ('$ComputerID')"
    }
   ]
  }
 ]
}