#
# Migration Script: Create Folder Structure and Set Ownership
# Generated: 2026-06-10T09:39:51.1005094Z
# Source: CLAWS Collection Details
# Computer: VARX
# Scan Path: G:\Group
# Inventory ID: f79fc86d-dddf-49ec-ac02-ee71b8a40483
#
# REVIEW THIS SCRIPT BEFORE RUNNING. Test on a small subset first.
#

$ErrorActionPreference = 'Stop'

# --- Configuration ---
$OwnerIdentity = 'BUILTIN\Administrators'

# --- Folder List ---
$Folders = @(
    'G:\Group'
    'G:\Group\Blue Prism for Implementation'
    'G:\Group\Client'
    'G:\Group\Millennium'
    'G:\Group\Client\Evansville'
    'G:\Group\Client\Formula'
    'G:\Group\Client\G6'
    'G:\Group\Client\PRP'
    'G:\Group\Client\Sessa'
    'G:\Group\Client\ThirdEyeCapital'
    'G:\Group\Client\WhiteHaven'
    'G:\Group\Millennium\Management'
    'C:\Windows\system32\spool\drivers'
    'G:\Group\Client\brigade\ADR'
    'G:\Group\Client\brigade\Audit Confirms New'
    'G:\Group\Client\brigade\Custodial Account Codes'
    'G:\Group\Client\brigade\GoRec'
    'G:\Group\Client\brigade\Issues Log'
    'G:\Group\Client\brigade\Phone numbers'
    'G:\Group\Client\brigade\PHYSICAL and PRIVATE deals'
    'G:\Group\Client\brigade\PnL changes for Rollfoward'
    'G:\Group\Client\brigade\Position Breaks Summaries'
    'G:\Group\Client\brigade\PPMs'
    'G:\Group\Client\brigade\TASKs archive'
    'G:\Group\Client\brigade\Team outing'
    'G:\Group\Client\brigade\TRS Reset'
    'G:\Group\Client\Formula\Audit Confirms'
    'G:\Group\Client\Formula\Daily Recs'
    'G:\Group\Client\Formula\Financials'
    'G:\Group\Client\Formula\RSM Share Roll'
    'G:\Group\Client\Iridian\Docs'
    'G:\Group\Client\Iridian\Procedures'
    'G:\Group\Client\PRP\ZIP'
    'G:\Group\Loan Processing Group (Toronto)\Farm_Bureau\Doyle'
    'G:\Group\Test\Manoj_Test_Noninherited\NonInherited'
    'G:\Group\Client\brigade\Bank Debt\ClearPar'
    'G:\Group\Client\Iridian\Archive\SALI'
    'G:\Group\Client\Iridian\GoApplications\GoBilling'
    'G:\Group\Client\PIMCO\NDA and Legal Structure\PMTG - S-11 Form_files'
    'G:\Group\Client\Platinum Funds\Audit\VAI Final Monthend Package 2007-2016'
    'G:\Group\Client\Vectors Research\Deauville\201503 Daily'
    'G:\Group\Test\Manoj_Test_Noninherited\Inherited\Nonhireted'
    'G:\Group\Test\Manoj_Test_Noninherited\NonInherited\Nonherited'
    'G:\Group\Client\400 Capital JS Investments\Activity JS\2013\DEC 2013'
    'G:\Group\Client\400 Capital JS Investments\Activity JS\2013\FEB 2014'
    'G:\Group\Client\400 Capital JS Investments\Activity JS\2013\NOV 2013'
    'G:\Group\Client\400 Capital JS Investments\Activity JS\2014\JAN 2014'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ADS_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AFFINIA_TLB1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AICHEM_2NDLIEN'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AICHEM_TLB, AI_TL1_B2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALBERTSONS_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALBERTSONS_TL3'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALCATEL-LUCENT_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALCATELLUCENT_TLC'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALCATELLUCENT_TLD'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALLIANT_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ALTICE_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AMC_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AMERIFORGE_2L'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AMERIFORGE_TL1, BL_AFGLOBAL_TL1B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_APEX_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_APPVION_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ARAMARK_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ARAMARK_TLC'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ARAMARK_TLD'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ARDENT_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ARMSTRONG_TLB1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ARRIS_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ASURION_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ATI_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AUDIOVISUAL_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AWAS_NEWTL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AXALTA_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_AZ_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_BASS_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_BOWIE_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_BOYD_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_BRIGHT_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_BURLINGTON_TLB2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CALPINE_TL_B3'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CARIBBEAN_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CBRICHARD_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CCC_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CCO_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CENTAUR_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CENTAUR_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CHARTER_TL_F'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CHTR_3RD'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CLEAR_TL1_D-EXT'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CLIPPER_TL, TCW_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_COLE_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_COMMSCOPE_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_COMPUCOM_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CONTAINER_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_COOPER_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CROWN_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CSM BAKERY_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CTI FOODS_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_CYANCO_TL1_B, TL_1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DAVE_NEWTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DAVITA_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DEL_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DELTA_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DELTA_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DIGITALGLOBE_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DINEEQUITY_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DJO_TL1stLien'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DONCASTERS_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DONCASTERS_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DUNKIN_B3'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DUPONT_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DYNEGY_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DYNEGY_TL1_B2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_DYNERGY_B2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_EAGLE_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_EAST_VALLEY_'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_EP_TL1_B3'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FAIRWAY_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FIRST_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FIRST_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FIRST_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FIRSTADVANTAG_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FIRSTDATA_EXT'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FOCUS_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FONTAINEB_DD_BOS & TL_BOS'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FORESIGHT_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FOX_TLB1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FREIF_NEWTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_FREIF_NEWTLC'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_GENESIS_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_GENESYS_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_GIM CHANNELVIEW_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_GLOBALCASH_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_GODADDY_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_GREENEDEN_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HARRAHS_TL_M1, M2, M3, M4, M5'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HAWKER_TL1_B-EXIT'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HCR_TL B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HEALOGICS_2L'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HEALOGICS_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HJHEINZ_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HLSS_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HOFFMASTER_2ND'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HOFFMASTER_TLA'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HUB_NEWTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HUBBARD_TLB_1L'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HUNTSMAN_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_HUNTSMAN_TLC'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_IMMUCOR_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_IMS_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_INC_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_INEOS_TL1, TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_INEOS_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_INTERACTIVE_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ISTAR_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_JCPENNEY_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_JO-ANN_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_KAR_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LA_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LASVEGAS_EXDD2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LAVENA_TLE'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LIGHTOWER_2NDTL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LINTV_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LIONS_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_LODGENET_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MACDERMID_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MANITOWOC_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MARSICO_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MEDIACOM_TLC'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MILACRON_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MIRROR_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MMODAL_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MONITRONICS_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MOXIE_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MTL_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MULTIPLAN_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_MURRAY_TL, TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NAVIOS_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NAVISTAR_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NEP_2L'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NEP_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NEXEO_TLB2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NUVEEN_NEW2ND'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NUVEEN_NEWTL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_NUVEEN_NEWTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_OCEANRIG_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_OCI_TL1_B1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_OCWEN_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_OTTER_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PACIFICDRILL_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PANDA_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PAR_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PAR_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PARTY_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PATHEON_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PHARMARES_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PLAINSEXP_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PLAYA_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_POWER_UNFUN_DD'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PQ_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PQ_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PRESTIGE_TLB1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_PVH_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_QUINTILES_TLB2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_REALOGY_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_REGAL_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_RITE_2L'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_RITE_TL6'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_RIVERBED_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_ROYAL_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SACYR_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SAGE_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SAUER_REV3'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SEAWORLD_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SEDGWICK_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SELECTMED_INCMTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SELECTMED_NEWTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SEMINOLE_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SEQUA_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SERVICEMSTR_NEWTL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SERVMASTER_LCB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SEVEN_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SHINGLE_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SILVER_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SIRVA_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_STALLION_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_STATE_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_STATION_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_STEWARD_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_STGEORGES_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SUMMIT_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SUMMIT_TLB2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SUNGARD_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SUNGARD_TLC'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SUPERVALU_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SURGICALCARE_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_SYNIVERSE_1L_DD'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TERVITA_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TESORO_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TOWER_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TOYSRUS_NEWTL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TRANSFIRST_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TRICORBRAUN_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TRINET_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_TWCC_TL1'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_UNITED_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_UNIVERSAL_NEWTLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_UNIVISION_TLC2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_UPC_TLAH'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_UPC_TLX'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_US AIR_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_USI_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_USPI_TL1_B'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_VANGUARD_TL1_NEW'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_VERTRUE_NEWTL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_VILLAGEROAD_TLB'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_VWR_TL1_B-NEW'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_WALTER_TL2'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_WENDYS_TL1_B-NEW'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_WEST_TL1_B9'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_WNA_TL'
    'G:\Group\Client\brigade\Bank Debt\0-Notices and FMs\BL_WPP_TL1'
    'G:\Group\Client\EIM\Funds\Beachpoint\Audit 2012'
    'G:\Group\Client\EIM\Funds\Beachpoint\Monthend\2013'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\140'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Balanced'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\GDH'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\GSS'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Neutral'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1216'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1217'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1218'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1220'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1223'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1224'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1226'
    'G:\Group\Client\Formula\Daily Recs\2013\Dec 13\Enhance\1227'
    'G:\Group\Client\Sessa\Month End\Prior Years\2016\12-2016\Secure Registered Envelope ENCRYPT Sessa Dec 2016 closing package_files'
    'G:\Group\Client\RA Capital\MONTH END\2015\10 OCT\RA I\BOSTON PRIVATE\Boston Private Bank & Trust Co.html LTD_files'
    'G:\Group\Client\RA Capital\MONTH END\2015\10 OCT\RA I\BOSTON PRIVATE\Boston Private Bank & Trust Co_files'
    'G:\Group\Client\RA Capital\MONTH END\2015\12 DEC\RA I LTD\BOSTON PRIVATE\Boston Private Bank & Trust Co LTD_files'
    'G:\Group\Client\RA Capital\MONTH END\2015\12 DEC\RA I\BOSTON PRIVATE\Boston Private Bank & Trust Co LP_files'
    'G:\Group\Client\RA Capital\MONTH END\2016\02 FEB\RA I LTD\BOSTON PRIVATE\Boston Private Bank & Trust Co LTD_files'
    'G:\Group\Client\RA Capital\MONTH END\2016\02 FEB\RA I\BOSTON PRIVATE\Boston Private Bank & Trust Co LP_files'
    'G:\Group\Client\RA Capital\MONTH END\2016\03 MAR\RA I LTD\BOSTON PRIVATE\Boston Private Bank & Trust Co_files'
    'G:\Group\Client\RA Capital\MONTH END\2016\03 MAR\RA I\BOSTON PRIVATE\Boston Private Bank & Trust Co_files'
    'G:\Group\Client\Solus PE\9. Solus Recovery SARL (Luxco)\FINANCIALS\2014\4- LuxCo\FA files\Luxco Payments 2014'
    'G:\Group\Client\Luminous\FINANCIAL STATEMENTS\2015\1 - Funds\C - Hedge Funds\1 - Altair Global Credit Opportunities Fund (A), LLC\Year End\Restored10282016'
    'G:\Group\Client\Luminous\FINANCIAL STATEMENTS\2015\1 - Funds\C - Hedge Funds\2 - Altair Global Credit Opportunities Fund (C), LLC\Year End\restored10282016.2'
    'G:\Group\Client\Luminous\FINANCIAL STATEMENTS\2015\1 - Funds\C - Hedge Funds\2 - Altair Global Credit Opportunities Fund (C), LLC\Year End\restored10282016.2\Year End'
)

# --- Resolve Owner Identity ---
try {
    $OwnerAccount = New-Object System.Security.Principal.NTAccount($OwnerIdentity)
    $null = $OwnerAccount.Translate([System.Security.Principal.SecurityIdentifier])
    Write-Host "Owner identity resolved: $OwnerIdentity" -ForegroundColor Green
}
catch {
    Write-Host "ERROR: Cannot resolve owner identity '$OwnerIdentity'." -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    exit 1
}

# --- Create Folders and Set Ownership ---
$Created = 0; $Skipped = 0; $Errors = 0
$Total = $Folders.Count
for ($i = 0; $i -lt $Total; $i++) {
    $FolderPath = $Folders[$i]
    Write-Progress -Activity 'Creating folders' -Status "$($i + 1) of $Total" -PercentComplete ((($i + 1) / $Total) * 100)
    try {
        if (-not (Test-Path -LiteralPath $FolderPath)) {
            $null = New-Item -Path $FolderPath -ItemType Directory -Force
            Write-Host "  [CREATED] $FolderPath" -ForegroundColor Green
            $Created++
        } else {
            Write-Host "  [EXISTS]  $FolderPath" -ForegroundColor Yellow
            $Skipped++
        }
        $Acl = Get-Acl -LiteralPath $FolderPath
        $Acl.SetOwner($OwnerAccount)
        Set-Acl -LiteralPath $FolderPath -AclObject $Acl
    } catch {
        Write-Host "  [ERROR]   $FolderPath - $($_.Exception.Message)" -ForegroundColor Red
        $Errors++
    }
}
Write-Progress -Activity 'Creating folders' -Completed

Write-Host ''
Write-Host '========================================' -ForegroundColor Cyan
Write-Host ' Migration Complete' -ForegroundColor Cyan
Write-Host '========================================' -ForegroundColor Cyan
Write-Host "  Total:   $Total"
Write-Host "  Created: $Created" -ForegroundColor Green
Write-Host "  Skipped: $Skipped" -ForegroundColor Yellow
Write-Host "  Errors:  $Errors" -ForegroundColor $(if ($Errors -gt 0) { 'Red' } else { 'Green' })
