USE [master]
GO

/****** Object:  Database [SUSDB_Reports]    Script Date: 4/10/2024 11:20:48 AM ******/
CREATE DATABASE [SUSDB_Reports]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUSDB_Reports', FILENAME = N'F:\DB_Data\SUSDB_Reports.mdf' , SIZE = 81552384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SUSDB_Reports_log', FILENAME = N'G:\DB_Log\SUSDB_Reports_log.ldf' , SIZE = 5251072KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SUSDB_Reports] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SUSDB_Reports].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SUSDB_Reports] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET ARITHABORT OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SUSDB_Reports] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SUSDB_Reports] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SUSDB_Reports] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SUSDB_Reports] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SUSDB_Reports] SET  MULTI_USER 
GO

ALTER DATABASE [SUSDB_Reports] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SUSDB_Reports] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SUSDB_Reports] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SUSDB_Reports] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SUSDB_Reports] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SUSDB_Reports] SET QUERY_STORE = OFF
GO

USE [SUSDB_Reports]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SUSDB_Reports] SET  READ_WRITE 
GO


