{
 "title": "FileStatReport",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "winventory", "query": "mssql" },
   {
    "name": "batchid",
    "label": "Batch ID",
    "query": "SELECT BatchId\nFROM FileSizes.dbo.ScanBatch"
   }
  ]
 },
 "panels": [
  {
   "title": " Batch Info",
   "type": "table",
   "description": "This panel displays the basic information from the file scan",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "FileSizes",
     "rawSql": "SELECT 'ServerName'     AS MetricName, b.ServerName     AS MetricValue FROM [FileSizes].dbo.ScanBatch b WHERE b.BatchId IN (${batchid:singlequote})\r\nUNION ALL\r\nSELECT 'CollectedAtUtc' AS MetricName, CONVERT(VARCHAR, b.CollectedAtUtc, 120) FROM [FileSizes].dbo.ScanBatch b WHERE b.BatchId IN (${batchid:singlequote})\r\nUNION ALL\r\nSELECT 'ToolName'       AS MetricName, b.ToolName       FROM [FileSizes].dbo.ScanBatch b WHERE b.BatchId IN (${batchid:singlequote})\r\nUNION ALL\r\nSELECT 'CollectedBy'    AS MetricName, b.CollectedBy    FROM [FileSizes].dbo.ScanBatch b WHERE b.BatchId IN (${batchid:singlequote})\r\nUNION ALL\r\nSELECT 'Volumes'        AS MetricName, CAST(COUNT(v.ScanVolumeId) AS VARCHAR) FROM [FileSizes].dbo.ScanBatch b\r\nLEFT JOIN [FileSizes].dbo.ScanVolume v ON v.BatchId = b.BatchId\r\nWHERE b.BatchId IN (${batchid:singlequote})\r\nGROUP BY b.BatchId\r\nUNION ALL\r\nSELECT 'TotalEntries'   AS MetricName, CAST(SUM(v.EntryCount) AS VARCHAR) FROM [FileSizes].dbo.ScanBatch b\r\nLEFT JOIN [FileSizes].dbo.ScanVolume v ON v.BatchId = b.BatchId\r\nWHERE b.BatchId IN (${batchid:singlequote})\r\nGROUP BY b.BatchId;\r\n"
    }
   ]
  },
  {
   "title": "Volume capacity summary ",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "FileSizes",
     "rawSql": "WITH LatestBatch AS (\r\n    SELECT ServerName, MAX(CollectedAtUtc) AS LatestScan\r\n    FROM FileSizes.dbo.ScanBatch\r\n    GROUP BY ServerName\r\n)\r\nSELECT\r\n    v.VolumeName,\r\n    v.VolumeLabel,\r\n    v.TotalSizeBytes / 1073741824.0   AS TotalGB,\r\n    v.FreeSizeBytes  / 1073741824.0   AS FreeGB,\r\n    CASE WHEN v.TotalSizeBytes > 0\r\n         THEN 100.0 * (v.TotalSizeBytes - v.FreeSizeBytes) / v.TotalSizeBytes\r\n         ELSE NULL\r\n    END AS PctUsed,\r\n    v.FileCount,\r\n    v.DirectoryCount,\r\n    v.ErrorCount\r\nFROM LatestBatch lb\r\nJOIN FileSizes.dbo.ScanBatch b ON b.ServerName = lb.ServerName\r\n                    AND b.CollectedAtUtc = lb.LatestScan\r\nJOIN FileSizes.dbo.ScanVolume v ON v.BatchId = b.BatchId\r\nwhere b.BatchId in (${batchid:singlequote})\r\nORDER BY b.ServerName, v.VolumeName;"
    }
   ]
  },
  {
   "title": "File type distribution (by extension)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "FileSizes",
     "rawSql": "\r\nSELECT\r\n    CASE\r\n        WHEN CHARINDEX('.', REVERSE(f.FileName)) > 0\r\n        THEN LOWER(RIGHT(f.FileName, CHARINDEX('.', REVERSE(f.FileName)) - 1))\r\n        ELSE '(no ext)'\r\n    END AS Extension,\r\n    COUNT(*)                            AS FileCount,\r\n    SUM(f.FileSize) / 1073741824.0      AS TotalGB,\r\n    AVG(f.FileSize) / 1048576.0         AS AvgSizeMB,\r\n    MAX(f.FileSize) / 1073741824.0      AS LargestGB\r\nFROM [FileSizes].dbo.FileEntry f\r\nWHERE f.BatchId IN (${batchid:singlequote})\r\n  AND f.IsDirectory = 0\r\n  AND f.FileSize IS NOT NULL\r\nGROUP BY\r\n    CASE\r\n        WHEN CHARINDEX('.', REVERSE(f.FileName)) > 0\r\n        THEN LOWER(RIGHT(f.FileName, CHARINDEX('.', REVERSE(f.FileName)) - 1))\r\n        ELSE '(no ext)'\r\n    END\r\nORDER BY TotalGB DESC;"
    }
   ]
  },
  {
   "title": "Duplicate file candidates (same name + size, different paths)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "FileSizes",
     "rawSql": "DECLARE @BatchId5 UNIQUEIDENTIFIER = '0416EF82-58FB-422E-ABA5-FC31FB81401B';  -- replace\r\nDECLARE @DupMinSizeMB BIGINT = 10;\r\n\r\nSELECT\r\n    f.FileName,\r\n    f.FileSize / 1048576.0 AS SizeMB,\r\n    COUNT(*)               AS CopyCount,\r\n    COUNT(*) * f.FileSize / 1073741824.0 AS WastedGB\r\nFROM [FileSizes].dbo.FileEntry f\r\nWHERE f.BatchId IN (${batchid:singlequote})\r\n  AND f.IsDirectory = 0\r\n  AND f.FileSize >= @DupMinSizeMB * 1048576\r\nGROUP BY f.FileName, f.FileSize\r\nHAVING COUNT(*) > 1\r\nORDER BY WastedGB DESC;"
    }
   ]
  },
  {
   "title": "Top 50 largest files ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "FileSizes",
     "rawSql": "SELECT TOP 50\r\n    f.Volume,\r\n    f.FullPath,\r\n    f.FileSize / 1073741824.0 AS SizeGB,\r\n    f.ModifiedTime,\r\n    f.AccessedTime\r\nFROM FileSizes.dbo.FileEntry f\r\nJOIN FileSizes.dbo.ScanBatch b ON b.BatchId = f.BatchId\r\nWHERE b.[BatchId] in (${batchid:singlequote})\r\n  AND f.IsDirectory = 0\r\nORDER BY f.FileSize DESC;"
    }
   ]
  },
  {
   "title": "Stale files: not modified in over 2 years, larger than 100 MB",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "FileSizes",
     "rawSql": "DECLARE @BatchId3 UNIQUEIDENTIFIER = (${batchid:singlequote});  -- replace\r\nDECLARE @StaleDate DATETIME2(0) = DATEADD(YEAR, -2, SYSUTCDATETIME());\r\nDECLARE @MinSizeMB BIGINT = 100;\r\n\r\nSELECT\r\n    f.Volume,\r\n    f.FullPath,\r\n    f.FileSize / 1048576.0     AS SizeMB,\r\n    f.ModifiedTime,\r\n    f.AccessedTime,\r\n    DATEDIFF(DAY, f.ModifiedTime, SYSUTCDATETIME()) AS DaysSinceModified\r\nFROM [FileSizes].dbo.FileEntry f\r\nWHERE f.BatchId = @BatchId3\r\n  AND f.IsDirectory = 0\r\n  AND f.FileSize >= @MinSizeMB * 1048576\r\n  AND f.ModifiedTime < @StaleDate\r\nORDER BY f.FileSize DESC;"
    }
   ]
  }
 ]
}